/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useCubeTexture  } from '@react-three/drei'
import {useFrame} from 'react-three-fiber'

export function VendingMachine(props) {
  const group = useRef()
  const envMap = useCubeTexture(["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"], { path: "/cubemap/" })

  const [reverse, setReverse] = useState(1);

  const { nodes, materials } = useGLTF('/Cola.gltf')
  useFrame(()=>  {
    group.current.rotation.y += .001 * reverse;
    if(group.current.rotation.y >=0.5) setReverse(-1);
    else if (group.current.rotation.y <=0) setReverse(1);
    }
  );

  useEffect(() => {
    materials['Material.001'].envMap = envMap;
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow material={materials['Material.001']} geometry={nodes.Cola.geometry} position={[0,0,0]} />
    </group>
  )
}

useGLTF.preload('/Cola.gltf')

export default VendingMachine
